document.addEventListener("DOMContentLoaded", async () => {
    const container = document.getElementById('dispatches-container');
    const articleContainer = document.getElementById('article-container');

    // 1. If we are on the Homepage, load the list of dispatches
    if (container) {
        try {
            // Fetch the list of files from the GitHub repository folder via Cloudflare/GitHub API or static index
            // For Pages CMS, we look at the content directory structure or use a fetch approach
            const response = await fetch('content/dispatches/');
            
            // Fallback if directory listing isn't directly exposed:
            // We can display a clean prompt if no posts are written yet.
            container.innerHTML = `
                <div class="dispatch-card">
                    <div class="dispatch-meta">
                        <span class="dispatch-date">Welcome</span>
                        <span class="dispatch-tag">Beginning</span>
                    </div>
                    <h3>First Dispatch Coming Soon</h3>
                    <p>This space is newly formed. Check back soon for the first reflection on modern chaos and interior quiet.</p>
                </div>
            `;
        } catch (error) {
            container.innerHTML = `<p class="loading-text">No dispatches found yet. Use Pages CMS to write your first piece.</p>`;
        }
    }

    // 2. If we are on the Reader page (dispatch.html), check for URL parameters to load a specific essay
    if (articleContainer) {
        const urlParams = new URLSearchParams(window.location.search);
        const slug = urlParams.get('slug');

        if (slug) {
            // Fetch the specific markdown file generated by Pages CMS
            try {
                const res = await fetch(`content/dispatches/${slug}.md`);
                const text = await res.text();
                
                // Simple parser for demonstration (title, date, body)
                document.getElementById('article-title').textContent = slug.replace(/-/g, ' ');
                document.getElementById('article-body').innerHTML = `<p>${text}</p>`;
            } catch (err) {
                document.getElementById('article-title').textContent = "Dispatch not found";
                document.getElementById('article-body').innerHTML = "<p>This dispatch could not be loaded.</p>";
            }
        }
    }
});
